apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "irsa-manager.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: irsa-manager
    app.kubernetes.io/part-of: irsa-manager
  {{- include "irsa-manager.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}