# permissions for end users to view irsas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: irsa-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: irsa-manager
    app.kubernetes.io/part-of: irsa-manager
    app.kubernetes.io/managed-by: kustomize
  name: irsa-viewer-role
rules:
  - apiGroups:
      - irsa-manager.kkb0318.github.io
    resources:
      - irsas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - irsa-manager.kkb0318.github.io
    resources:
      - irsas/status
    verbs:
      - get
