# permissions for end users to edit irsasetups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: irsasetup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: irsa-manager
    app.kubernetes.io/part-of: irsa-manager
    app.kubernetes.io/managed-by: kustomize
  name: irsasetup-editor-role
rules:
- apiGroups:
  - irsa.kkb0318.github.io
  resources:
  - irsasetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - irsa.kkb0318.github.io
  resources:
  - irsasetups/status
  verbs:
  - get
